package controlador;

import org.openqa.selenium.By;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class CookieDriver {

    private WebDriver driver;

    public CookieDriver(){
        driver = new EdgeDriver();
    }

    public void ventanaGrande(){
        driver.manage().window().maximize();
    }

    public void web(){
        driver.get("https://orteil.dashnet.org/cookieclicker/");
    }

    public void wait5(){
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div[3]/div[2]/div[1]/div[2]/div[2]/button[1]/p")));
    }

    public void aceptaCookies(){
        driver.findElement(By.xpath("/html/body/div[3]/div[2]/div[1]/div[2]/div[2]/button[1]/p")).click();
        driver.manage().deleteAllCookies();
    }

    public void cargaPartida(){
        Actions action = new Actions(driver);
        action.keyDown(Keys.CONTROL).sendKeys("O").keyUp(Keys.CONTROL).build().perform();
        driver.findElement(By.id("textareaPrompt")).sendKeys("Mi4wNDh8fDE2Nzk4NDA3OTc2OTc7MTY3OTg0MDc5NzY5NzsxNjgxOTAwMzI2NDUzO0hlbGxhIE15c3Rlcnk7a3BsdWd8MDExMTAwMDAxMDAwMDAxMDAxMDEwMTEwMDAxfDE2MzE2MzYyMTczMjE4MDgyMDAwMDsxLjc2NjEwNTM2OTk4NDQ5MTdlKzIyOzMxNzEwNTY7Mjk4MzsxLjA0ODU0NzM3OTQxNDIxODZlKzIyOzg4OTswOzA7MDswOzA7MDswOy0xOzA7Mjk4MzswOzA7MDswOy0xOzA7OzA7MDswOzA7MDswOzA7LTE7LTE7LTE7LTE7LTE7MDswOzA7MDs1MDswOzA7NjsyMjsxNjgxODE0Mzc5NDU5OzA7MDs7NDE7MDswOzYzMzUzMDgxODM5NTMyNTY7NTA7fDMwMCwzMTgsOTkwMjc3NzA2MTU5Mzg2NDAwMCwyLCwwLDMwMDszMDAsMzAzLDI5MDI0OTg1MjI4NDY5NjIwMCwxLCwxLDMwMDsyNzAsMjc0LDQ5OTI1ODI5NzE1MTgwLDEsMTY4MTkwMDUyMjY4MTowOjE2ODA3ODQxMjkyMjY6MDo0OjQ6MDowOjE2ODA3ODQxMjkyMjY6IDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAgMDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6LDEsMjcwOzI2MCwyNjAsMTY0MzM4MjgyMjQ2NDc3LDEsLDEsMjYwOzI1MCwyNTAsNDY2NjI1MzI3NTk4MDkwLDEsLDEsMjUwOzIyMCwyMjEsMTY0Njg4NjU2MjU2MzgxNiwxLDA6MDoxOjA6MTogNDUyMjo1Oi04MDoxODQ6MDowOjA6MCE2NjA3OjE6LTI0NzozNjk6MDowOjA6MCEzMTY1OjA6LTEwOjU0NTowOjA6MDowITY0MDoyOjEzOjIzNDowOjA6MDowITUwNjY6MTotMTgyOjY2NTowOjA6MDowITQ2ODg6MTotNzg6ODI6MDowOjA6MCE0Njc1OjQ6LTEwMTozNDg6MDowOjA6MCE5NzUwOjM6LTIzNjoxMDc6MDowOjA6MCEyODI6NTotMTkzOjMzOTowOjA6MDowITY5Njk6MTotNDg6NTk4OjA6MDowOjAhMzE0ODoyOi0yMDQ6NTg3OjA6MDowOjAhMTU0MzI6MTotNzY6NTM4OjA6MDowOjAhODc1ODozOi0xNDQ6Njk4OjA6MDowOjAhNjQ5Njo1OjU1OjE3MzowOjA6MDowITEzNTk0OjI6LTc5Ojc1OjA6MDowOjAhMTMyODg6MjotNzk6NDM1OjA6MTowOjAhMTExMTI6NDotNTE6Mzg4OjA6MTowOjAhIDEsMSwyMjA7MjAwLDIwMCw2NzUxNjA3MzQ0NDI2NTUwLDEsMS8tMS8tMSAzIDE2ODEyODQxMjM0MDkgMSwwLDIwMDsxODAsMTgwLDIyMjE3MjgwNjgyNjIyMTA0LDEsNjUgMCAwIDAsMSwxODA7MTcwLDE3MCw4MTI0MzY4MTg3MTQ5NjM4MCwxLCwxLDE3MDsxNTAsMTUwLDMxODE1MTcxMjU5NDM4NzUwMCwxLCwxLDE1MDsxMzAsMTMwLDE0NTYxMzAxNDYwMzAzODMwMDAsMCwsMSwxMzA7MTEwLDExMCw2MDQwODYzNjgwMTM2NTY2MDAwLDAsLDEsMTEwOzEwMCwxMDAsMjQ3NTIyNzgzNDA3MDgxOTIwMDAsMCwsMSwxMDA7ODAsODAsOTQ2ODM5MTI2OTQyNjYyNzAwMDAsMSwsMSw4MDs2MCw2MCwzNzQxOTc0MTM4NjYxMjc5MDAwMDAsMSwsMSw2MDs0MCw0MCwxLjQ5MzkyMDYyMjM2NTM5NDllKzIxLDEsLDEsNDA7MTAsMTAsMzgzMjkwNzQwMTUwODk2NTYwMDAwLDEsLDAsMTA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMTExMTExMTEwMDExMTExMTAwMDAwMDExMDAxMTExMTEwMDExMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMTEwMDAwMDAwMDAwMDAxMTAwMDAxMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAxMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTEwMTAxMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMDAwMDAwMDAwMDAwMDAxMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfDExMTExMTExMTExMTExMDAxMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAxMTEwMTExMTEwMTAwMDEwMTEwMDExMTEwMDEwMDAwMDAxMTEwMTAwMDAwMDAwMDAxMTExMTAwMDExMDAxMDAwMDAxMDAwMDAwMDAwMDAxMTEwMTExMTAwMDAwMDAwMDAwMDAxMTEwMDExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDExMTAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMTEwMTAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMTAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8fA%3D%3D%21END%21");
        action.sendKeys(Keys.ENTER).build().perform();
    }

    public void clickBigCookie(){
        try {
            driver.findElement(By.id("bigCookie")).click();
        } catch (ElementClickInterceptedException e) {
            System.err.println("No deja click en la big cookie " + LocalDateTime.now().format(DateTimeFormatter.ISO_TIME));
        } catch (Exception e) {
            System.err.println("ERRORRR");
            System.err.println(e.initCause(e));
        }
        try {
            //click goldenCookie
            driver.findElement(By.xpath("/html/body/div[2]/div[2]/div[5]/div")).click();
            System.out.println("Coookie! " + LocalDateTime.now().format(DateTimeFormatter.ISO_TIME));

        } catch (Exception e) {

        }
    }

    public void cerrarDriver(){
        driver.close();
    }


}
